# Generated by Django 6.0.4 on 2026-05-09 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DefectReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("subcategory", models.CharField(max_length=100)),
                ("specific_reason", models.CharField(max_length=200)),
                ("machine_types", models.JSONField(blank=True, default=list)),
                ("machine_ids", models.JSONField(blank=True, default=list)),
                ("part_ids", models.JSONField(blank=True, default=list)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Die",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("die_number", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("machine_id", models.CharField(max_length=50, unique=True)),
                ("type", models.CharField(max_length=50)),
                ("ideal_cycle_time", models.FloatField(blank=True, null=True)),
                ("default_shift_time", models.IntegerField(default=480)),
                ("status", models.CharField(default="idle", max_length=20)),
                ("active", models.BooleanField(default=True)),
                ("image", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Operator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("employee_id", models.CharField(max_length=50, unique=True)),
                ("role", models.CharField(max_length=50)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProcessReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("machine_types", models.JSONField(blank=True, default=list)),
                ("machine_ids", models.JSONField(blank=True, default=list)),
                ("part_ids", models.JSONField(blank=True, default=list)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="DowntimeReasonItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("requires_extra_field", models.BooleanField(default=False)),
                (
                    "extra_field_label",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("machine_types", models.JSONField(blank=True, default=list)),
                ("machine_ids", models.JSONField(blank=True, default=list)),
                ("active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="production.downtimereasonitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DowntimeEventHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operator_name", models.CharField(max_length=100)),
                ("date", models.DateField()),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("morning", "Morning"),
                            ("afternoon", "Afternoon"),
                            ("night", "Night"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("duration", models.IntegerField()),
                ("reason_category", models.CharField(max_length=100)),
                (
                    "reason_subsystem",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "reason_component",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "reason_specific_item",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("reason_full_path", models.CharField(max_length=300)),
                ("comment", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.machine",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("part_number", models.CharField(max_length=50, unique=True)),
                ("cycle_time", models.FloatField()),
                ("active", models.BooleanField(default=True)),
                ("image", models.URLField(blank=True, null=True)),
                ("dies", models.ManyToManyField(blank=True, to="production.die")),
            ],
        ),
        migrations.AddField(
            model_name="machine",
            name="supported_parts",
            field=models.ManyToManyField(blank=True, to="production.part"),
        ),
        migrations.CreateModel(
            name="PartProductionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("die", models.CharField(blank=True, max_length=100, null=True)),
                ("date", models.DateField()),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("morning", "Morning"),
                            ("afternoon", "Afternoon"),
                            ("night", "Night"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[("PASS", "Pass"), ("NOT GOOD", "Not Good")],
                        max_length=20,
                    ),
                ),
                (
                    "defect_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "defect_subcategory",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "defect_specific_reason",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.machine",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="production.operator",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="production.part",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("morning", "Morning"),
                            ("afternoon", "Afternoon"),
                            ("night", "Night"),
                        ],
                        max_length=20,
                    ),
                ),
                ("planned_production_time", models.IntegerField()),
                ("counter_start", models.IntegerField(default=0)),
                ("counter_end", models.IntegerField(default=0)),
                ("gross_count", models.IntegerField(default=0)),
                ("excluded_shots", models.IntegerField(default=0)),
                ("net_production", models.IntegerField(default=0)),
                ("total_count", models.IntegerField(default=0)),
                ("target_output", models.IntegerField(default=0)),
                ("performance", models.FloatField(default=0.0)),
                ("downtime", models.IntegerField(default=0)),
                ("good_count", models.IntegerField(default=0)),
                ("defect_count", models.IntegerField(default=0)),
                ("operator_name", models.CharField(max_length=100)),
                ("notes", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("downtime_events", models.JSONField(blank=True, default=list)),
                ("defects", models.JSONField(blank=True, default=list)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="production.machine",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScheduledDowntime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("duration", models.IntegerField()),
                ("reason", models.CharField(max_length=200)),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.machine",
                    ),
                ),
            ],
        ),
    ]
