# Generated by Django 6.0.4 on 2026-05-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partproductionhistory",
            name="operator",
        ),
        migrations.AddField(
            model_name="partproductionhistory",
            name="operator_name",
            field=models.CharField(default="Unknown", max_length=100),
            preserve_default=False,
        ),
    ]
