# Generated by Django 6.0.4 on 2026-05-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0002_remove_partproductionhistory_operator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downtimeeventhistory",
            name="end_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="downtimeeventhistory",
            name="start_time",
            field=models.TimeField(),
        ),
    ]
