# Generated by Django 6.0.4 on 2026-08-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_downtimeeventhistory_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectreason',
            name='specific_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
