# Generated by Django 6.0.4 on 2026-08-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OcrJobRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=200, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=300)),
                ('ocr_status', models.CharField(default='queued', max_length=20)),
                ('ocr_stage', models.CharField(blank=True, default='', max_length=40)),
                ('import_status', models.CharField(choices=[('not_imported', 'Not imported'), ('imported', 'Imported'), ('stale', 'Stale')], default='not_imported', max_length=20)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('last_imported_at', models.DateTimeField(blank=True, null=True)),
                ('last_import_rejects', models.BooleanField(default=False)),
                ('last_import_downtime', models.BooleanField(default=False)),
                ('merged_json_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
